name: build check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "homework/**", "homeworks/**" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: detekt
        run: |
          chmod +x gradlew
          ./gradlew detekt

      - name: build
        run: ./gradlew buildDebug

      - name: upload reports
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3.1.0
        with:
          path: app/build/reports/detekt/detekt.html
          if-no-files-found: ignore
          retention-days: 7
